// Generated by swift_ffi. Do not edit.
//
// TypeScript bindings for the `SwiftUI` Swift module compiled to a
// WebAssembly reactor. Load with:
//
//   const bridge = await load(wasmBytesOrModule);
//
// Ownership follows the swift-java model: wrapper objects own a +1 handle
// to the Swift instance. Release deterministically with `close()` (or a
// `using` declaration); a FinalizationRegistry backstop releases leaked
// wrappers after they are garbage collected.
//
// The shared runtime (swift_ffi/runtime/ts) is staged next to this file
// by the wasm library macro; bridges in one directory share the one copy.
import { BlobReader, Runtime, SwiftError, Tags, Types, decodeWith, decoder, encodeErrorBlob, encodeWith, encoder, foreignObjects, registerForeign, registry, stageBytes, stageString, takeBytes, wasiShim, } from "./swift_ffi_runtime.js?v=179e41bc";
// Re-exported so consumers keep importing them from this module.
export { Types } from "./swift_ffi_runtime.js?v=179e41bc";
/** The runtime type token for `TextMetrics` (generic calls). */
export const TextMetricsType = {
    encode(w, v) {
        w.header(Tags.struct, 2);
        w.i64(2n);
        Types.double.encode(w, v.width);
        Types.double.encode(w, v.height);
    },
    decode(r) {
        const tag = r.i32();
        r.i32();
        if (tag !== Tags.struct)
            throw new SwiftError("expected TextMetrics");
        r.i64();
        const width = Types.double.decode(r);
        const height = Types.double.decode(r);
        return { width, height };
    },
};
/** The runtime type token for `ImageInfoValue` (generic calls). */
export const ImageInfoValueType = {
    encode(w, v) {
        w.header(Tags.struct, 0);
        w.i64(3n);
        Types.int32.encode(w, v.state);
        Types.double.encode(w, v.width);
        Types.double.encode(w, v.height);
    },
    decode(r) {
        const tag = r.i32();
        r.i32();
        if (tag !== Tags.struct)
            throw new SwiftError("expected ImageInfoValue");
        r.i64();
        const state = Types.int32.decode(r);
        const width = Types.double.decode(r);
        const height = Types.double.decode(r);
        return { state, width, height };
    },
};
/** The runtime type token for `StoredValue` (generic calls). */
export const StoredValueType = {
    encode(w, v) {
        w.header(Tags.struct, 1);
        w.i64(2n);
        Types.bool.encode(w, v.exists);
        Types.string.encode(w, v.contents);
    },
    decode(r) {
        const tag = r.i32();
        r.i32();
        if (tag !== Tags.struct)
            throw new SwiftError("expected StoredValue");
        r.i64();
        const exists = Types.bool.decode(r);
        const contents = Types.string.decode(r);
        return { exists, contents };
    },
};
export const P2PRCDependencyKeyType = {
    encode(w, v) {
        Types.string.encode(w, v);
    },
    decode(r) {
        return Types.string.decode(r);
    },
};
export class SwiftP2PRCHost {
    handle;
    runtime;
    /** @internal Takes ownership of a +1 handle. */
    constructor(runtime, handle) {
        this.runtime = runtime;
        this.handle = handle;
        registry.register(this, () => runtime.call("swift_ffi_swiftui_P2PRCHost_release", handle), this);
    }
    /** @internal */
    borrowHandle() {
        if (this.handle === 0)
            throw new Error("P2PRCHost used after close()");
        return this.handle;
    }
    /** Releases the underlying Swift instance. Idempotent. */
    close() {
        if (this.handle !== 0) {
            registry.unregister(this);
            this.runtime.call("swift_ffi_swiftui_P2PRCHost_release", this.handle);
            this.handle = 0;
        }
    }
    [Symbol.dispose]() {
        this.close();
    }
    createOffer(requestID) {
        const handle = this.borrowHandle();
        this.runtime.call("swift_ffi_swiftui_P2PRCHost_createOffer", handle, requestID);
    }
    acceptOffer(requestID, blob) {
        const handle = this.borrowHandle();
        const b1 = stageString(this.runtime, blob);
        this.runtime.call("swift_ffi_swiftui_P2PRCHost_acceptOffer", handle, requestID, b1.ptr, b1.len);
        b1.drop();
    }
    acceptAnswer(requestID, blob) {
        const handle = this.borrowHandle();
        const b1 = stageString(this.runtime, blob);
        this.runtime.call("swift_ffi_swiftui_P2PRCHost_acceptAnswer", handle, requestID, b1.ptr, b1.len);
        b1.drop();
    }
    sendFrame(text) {
        const handle = this.borrowHandle();
        const b0 = stageString(this.runtime, text);
        this.runtime.call("swift_ffi_swiftui_P2PRCHost_sendFrame", handle, b0.ptr, b0.len);
        b0.drop();
    }
    save(key, value) {
        const handle = this.borrowHandle();
        const b0 = stageString(this.runtime, key);
        const b1 = stageString(this.runtime, value);
        this.runtime.call("swift_ffi_swiftui_P2PRCHost_save", handle, b0.ptr, b0.len, b1.ptr, b1.len);
        b0.drop();
        b1.drop();
    }
    load(requestID, key) {
        const handle = this.borrowHandle();
        const b1 = stageString(this.runtime, key);
        this.runtime.call("swift_ffi_swiftui_P2PRCHost_load", handle, requestID, b1.ptr, b1.len);
        b1.drop();
    }
    pageURL(requestID) {
        const handle = this.borrowHandle();
        this.runtime.call("swift_ffi_swiftui_P2PRCHost_pageURL", handle, requestID);
    }
    openingHash(requestID) {
        const handle = this.borrowHandle();
        this.runtime.call("swift_ffi_swiftui_P2PRCHost_openingHash", handle, requestID);
    }
    setHash(value) {
        const handle = this.borrowHandle();
        const b0 = stageString(this.runtime, value);
        this.runtime.call("swift_ffi_swiftui_P2PRCHost_setHash", handle, b0.ptr, b0.len);
        b0.drop();
    }
    publishAnswer(blob) {
        const handle = this.borrowHandle();
        const b0 = stageString(this.runtime, blob);
        this.runtime.call("swift_ffi_swiftui_P2PRCHost_publishAnswer", handle, b0.ptr, b0.len);
        b0.drop();
    }
    drawQR(elementID, text) {
        const handle = this.borrowHandle();
        const b0 = stageString(this.runtime, elementID);
        const b1 = stageString(this.runtime, text);
        this.runtime.call("swift_ffi_swiftui_P2PRCHost_drawQR", handle, b0.ptr, b0.len, b1.ptr, b1.len);
        b0.drop();
        b1.drop();
    }
}
export class SwiftGPUWebHost {
    handle;
    runtime;
    /** @internal Takes ownership of a +1 handle. */
    constructor(runtime, handle) {
        this.runtime = runtime;
        this.handle = handle;
        registry.register(this, () => runtime.call("swift_ffi_swiftui_GPUWebHost_release", handle), this);
    }
    /** @internal */
    borrowHandle() {
        if (this.handle === 0)
            throw new Error("GPUWebHost used after close()");
        return this.handle;
    }
    /** Releases the underlying Swift instance. Idempotent. */
    close() {
        if (this.handle !== 0) {
            registry.unregister(this);
            this.runtime.call("swift_ffi_swiftui_GPUWebHost_release", this.handle);
            this.handle = 0;
        }
    }
    [Symbol.dispose]() {
        this.close();
    }
    gpuCreateTexture(id, width, height, rgba) {
        const handle = this.borrowHandle();
        const b3 = stageBytes(this.runtime, rgba);
        this.runtime.call("swift_ffi_swiftui_GPUWebHost_gpuCreateTexture", handle, id, width, height, b3.ptr, b3.len);
        b3.drop();
    }
    gpuDestroyTexture(id) {
        const handle = this.borrowHandle();
        this.runtime.call("swift_ffi_swiftui_GPUWebHost_gpuDestroyTexture", handle, id);
    }
    gpuBeginFrame(red, green, blue, alpha) {
        const handle = this.borrowHandle();
        this.runtime.call("swift_ffi_swiftui_GPUWebHost_gpuBeginFrame", handle, red, green, blue, alpha);
    }
    gpuSetTransform(matrix) {
        const handle = this.borrowHandle();
        const b0 = stageBytes(this.runtime, matrix);
        this.runtime.call("swift_ffi_swiftui_GPUWebHost_gpuSetTransform", handle, b0.ptr, b0.len);
        b0.drop();
    }
    gpuDrawTextured(id, vertices) {
        const handle = this.borrowHandle();
        const b1 = stageBytes(this.runtime, vertices);
        this.runtime.call("swift_ffi_swiftui_GPUWebHost_gpuDrawTextured", handle, id, b1.ptr, b1.len);
        b1.drop();
    }
    gpuDrawColor(vertices) {
        const handle = this.borrowHandle();
        const b0 = stageBytes(this.runtime, vertices);
        this.runtime.call("swift_ffi_swiftui_GPUWebHost_gpuDrawColor", handle, b0.ptr, b0.len);
        b0.drop();
    }
    gpuDrawRects(vertices) {
        const handle = this.borrowHandle();
        const b0 = stageBytes(this.runtime, vertices);
        this.runtime.call("swift_ffi_swiftui_GPUWebHost_gpuDrawRects", handle, b0.ptr, b0.len);
        b0.drop();
    }
    gpuSetScissor(x, y, width, height) {
        const handle = this.borrowHandle();
        this.runtime.call("swift_ffi_swiftui_GPUWebHost_gpuSetScissor", handle, x, y, width, height);
    }
    gpuClearScissor() {
        const handle = this.borrowHandle();
        this.runtime.call("swift_ffi_swiftui_GPUWebHost_gpuClearScissor", handle);
    }
    gpuEndFrame() {
        const handle = this.borrowHandle();
        this.runtime.call("swift_ffi_swiftui_GPUWebHost_gpuEndFrame", handle);
    }
}
export class SwiftWebHost {
    handle;
    runtime;
    /** @internal Takes ownership of a +1 handle. */
    constructor(runtime, handle) {
        this.runtime = runtime;
        this.handle = handle;
        registry.register(this, () => runtime.call("swift_ffi_swiftui_WebHost_release", handle), this);
    }
    /** @internal */
    borrowHandle() {
        if (this.handle === 0)
            throw new Error("WebHost used after close()");
        return this.handle;
    }
    /** Releases the underlying Swift instance. Idempotent. */
    close() {
        if (this.handle !== 0) {
            registry.unregister(this);
            this.runtime.call("swift_ffi_swiftui_WebHost_release", this.handle);
            this.handle = 0;
        }
    }
    [Symbol.dispose]() {
        this.close();
    }
    measureText(text, fontSize, weight, wrapWidth) {
        const handle = this.borrowHandle();
        const b0 = stageString(this.runtime, text);
        const r = this.runtime.call("swift_ffi_swiftui_WebHost_measureText", handle, b0.ptr, b0.len, fontSize, weight, wrapWidth);
        b0.drop();
        return decodeWith(TextMetricsType, takeBytes(this.runtime, r));
    }
    imageInfo(source, isRemote) {
        const handle = this.borrowHandle();
        const b0 = stageString(this.runtime, source);
        const r = this.runtime.call("swift_ffi_swiftui_WebHost_imageInfo", handle, b0.ptr, b0.len, isRemote ? 1 : 0);
        b0.drop();
        return decodeWith(ImageInfoValueType, takeBytes(this.runtime, r));
    }
    syncHostViews(viewsJSON) {
        const handle = this.borrowHandle();
        const b0 = stageString(this.runtime, viewsJSON);
        this.runtime.call("swift_ffi_swiftui_WebHost_syncHostViews", handle, b0.ptr, b0.len);
        b0.drop();
    }
    beginTextInput(text, x, y, width, height, fontSize) {
        const handle = this.borrowHandle();
        const b0 = stageString(this.runtime, text);
        this.runtime.call("swift_ffi_swiftui_WebHost_beginTextInput", handle, b0.ptr, b0.len, x, y, width, height, fontSize);
        b0.drop();
    }
    endTextInput() {
        const handle = this.borrowHandle();
        this.runtime.call("swift_ffi_swiftui_WebHost_endTextInput", handle);
    }
    scheduleRender() {
        const handle = this.borrowHandle();
        this.runtime.call("swift_ffi_swiftui_WebHost_scheduleRender", handle);
    }
    setColorScheme(dark) {
        const handle = this.borrowHandle();
        this.runtime.call("swift_ffi_swiftui_WebHost_setColorScheme", handle, dark ? 1 : 0);
    }
    now() {
        const handle = this.borrowHandle();
        const r = this.runtime.call("swift_ffi_swiftui_WebHost_now", handle);
        return r;
    }
    rasterize(spec) {
        const handle = this.borrowHandle();
        const b0 = stageString(this.runtime, spec);
        const r = this.runtime.call("swift_ffi_swiftui_WebHost_rasterize", handle, b0.ptr, b0.len);
        b0.drop();
        return takeBytes(this.runtime, r);
    }
    storageGet(key) {
        const handle = this.borrowHandle();
        const b0 = stageString(this.runtime, key);
        const r = this.runtime.call("swift_ffi_swiftui_WebHost_storageGet", handle, b0.ptr, b0.len);
        b0.drop();
        return decodeWith(StoredValueType, takeBytes(this.runtime, r));
    }
    storageSet(key, value) {
        const handle = this.borrowHandle();
        const b0 = stageString(this.runtime, key);
        const b1 = stageString(this.runtime, value);
        this.runtime.call("swift_ffi_swiftui_WebHost_storageSet", handle, b0.ptr, b0.len, b1.ptr, b1.len);
        b0.drop();
        b1.drop();
    }
    log(message) {
        const handle = this.borrowHandle();
        const b0 = stageString(this.runtime, message);
        this.runtime.call("swift_ffi_swiftui_WebHost_log", handle, b0.ptr, b0.len);
        b0.drop();
    }
    openURL(url) {
        const handle = this.borrowHandle();
        const b0 = stageString(this.runtime, url);
        this.runtime.call("swift_ffi_swiftui_WebHost_openURL", handle, b0.ptr, b0.len);
        b0.drop();
    }
    platformCommand(key, value) {
        const handle = this.borrowHandle();
        const b0 = stageString(this.runtime, key);
        const b1 = stageString(this.runtime, value);
        this.runtime.call("swift_ffi_swiftui_WebHost_platformCommand", handle, b0.ptr, b0.len, b1.ptr, b1.len);
        b0.drop();
        b1.drop();
    }
    epochMillis() {
        const handle = this.borrowHandle();
        const r = this.runtime.call("swift_ffi_swiftui_WebHost_epochMillis", handle);
        return r;
    }
    renderTree(tree) {
        const handle = this.borrowHandle();
        const b0 = stageBytes(this.runtime, tree);
        this.runtime.call("swift_ffi_swiftui_WebHost_renderTree", handle, b0.ptr, b0.len);
        b0.drop();
    }
}
/** Builders wrapping host implementations for injection. */
export const Dependencies = {
    p2PRCHost: (provide, lazy = true) => ({
        ordinal: 1,
        lazy,
        dispatcher: dependencyDispatcher_P2PRCHost(provide),
    }),
    gPUWebHost: (provide, lazy = true) => ({
        ordinal: 0,
        lazy,
        dispatcher: dependencyDispatcher_GPUWebHost(provide),
    }),
    webHost: (provide, lazy = true) => ({
        ordinal: 2,
        lazy,
        dispatcher: dependencyDispatcher_WebHost(provide),
    }),
};
function dependencyDispatcher_P2PRCHost(provide) {
    let impl;
    return (args) => {
        if (!impl)
            impl = provide();
        const r = new BlobReader(args);
        switch (Types.int32.decode(r)) {
            case 0: {
                const a0 = Types.int32.decode(r);
                impl.createOffer(a0);
                return new Uint8Array(0);
            }
            case 1: {
                const a0 = Types.int32.decode(r);
                const a1 = Types.string.decode(r);
                impl.acceptOffer(a0, a1);
                return new Uint8Array(0);
            }
            case 2: {
                const a0 = Types.int32.decode(r);
                const a1 = Types.string.decode(r);
                impl.acceptAnswer(a0, a1);
                return new Uint8Array(0);
            }
            case 3: {
                const a0 = Types.string.decode(r);
                impl.sendFrame(a0);
                return new Uint8Array(0);
            }
            case 4: {
                const a0 = Types.string.decode(r);
                const a1 = Types.string.decode(r);
                impl.save(a0, a1);
                return new Uint8Array(0);
            }
            case 5: {
                const a0 = Types.int32.decode(r);
                const a1 = Types.string.decode(r);
                impl.load(a0, a1);
                return new Uint8Array(0);
            }
            case 6: {
                const a0 = Types.int32.decode(r);
                impl.pageURL(a0);
                return new Uint8Array(0);
            }
            case 7: {
                const a0 = Types.int32.decode(r);
                impl.openingHash(a0);
                return new Uint8Array(0);
            }
            case 8: {
                const a0 = Types.string.decode(r);
                impl.setHash(a0);
                return new Uint8Array(0);
            }
            case 9: {
                const a0 = Types.string.decode(r);
                impl.publishAnswer(a0);
                return new Uint8Array(0);
            }
            case 10: {
                const a0 = Types.string.decode(r);
                const a1 = Types.string.decode(r);
                impl.drawQR(a0, a1);
                return new Uint8Array(0);
            }
        }
        throw new SwiftError("unknown method ordinal");
    };
}
function dependencyDispatcher_GPUWebHost(provide) {
    let impl;
    return (args) => {
        if (!impl)
            impl = provide();
        const r = new BlobReader(args);
        switch (Types.int32.decode(r)) {
            case 0: {
                const a0 = Types.int32.decode(r);
                const a1 = Types.int32.decode(r);
                const a2 = Types.int32.decode(r);
                const a3 = Types.bytes.decode(r);
                impl.gpuCreateTexture(a0, a1, a2, a3);
                return new Uint8Array(0);
            }
            case 1: {
                const a0 = Types.int32.decode(r);
                impl.gpuDestroyTexture(a0);
                return new Uint8Array(0);
            }
            case 2: {
                const a0 = Types.double.decode(r);
                const a1 = Types.double.decode(r);
                const a2 = Types.double.decode(r);
                const a3 = Types.double.decode(r);
                impl.gpuBeginFrame(a0, a1, a2, a3);
                return new Uint8Array(0);
            }
            case 3: {
                const a0 = Types.bytes.decode(r);
                impl.gpuSetTransform(a0);
                return new Uint8Array(0);
            }
            case 4: {
                const a0 = Types.int32.decode(r);
                const a1 = Types.bytes.decode(r);
                impl.gpuDrawTextured(a0, a1);
                return new Uint8Array(0);
            }
            case 5: {
                const a0 = Types.bytes.decode(r);
                impl.gpuDrawColor(a0);
                return new Uint8Array(0);
            }
            case 6: {
                const a0 = Types.bytes.decode(r);
                impl.gpuDrawRects(a0);
                return new Uint8Array(0);
            }
            case 7: {
                const a0 = Types.int32.decode(r);
                const a1 = Types.int32.decode(r);
                const a2 = Types.int32.decode(r);
                const a3 = Types.int32.decode(r);
                impl.gpuSetScissor(a0, a1, a2, a3);
                return new Uint8Array(0);
            }
            case 8: {
                impl.gpuClearScissor();
                return new Uint8Array(0);
            }
            case 9: {
                impl.gpuEndFrame();
                return new Uint8Array(0);
            }
        }
        throw new SwiftError("unknown method ordinal");
    };
}
function dependencyDispatcher_WebHost(provide) {
    let impl;
    return (args) => {
        if (!impl)
            impl = provide();
        const r = new BlobReader(args);
        switch (Types.int32.decode(r)) {
            case 0: {
                const a0 = Types.string.decode(r);
                const a1 = Types.double.decode(r);
                const a2 = Types.int32.decode(r);
                const a3 = Types.double.decode(r);
                return encodeWith(TextMetricsType, impl.measureText(a0, a1, a2, a3));
            }
            case 1: {
                const a0 = Types.string.decode(r);
                const a1 = Types.bool.decode(r);
                return encodeWith(ImageInfoValueType, impl.imageInfo(a0, a1));
            }
            case 2: {
                const a0 = Types.string.decode(r);
                impl.syncHostViews(a0);
                return new Uint8Array(0);
            }
            case 3: {
                const a0 = Types.string.decode(r);
                const a1 = Types.double.decode(r);
                const a2 = Types.double.decode(r);
                const a3 = Types.double.decode(r);
                const a4 = Types.double.decode(r);
                const a5 = Types.double.decode(r);
                impl.beginTextInput(a0, a1, a2, a3, a4, a5);
                return new Uint8Array(0);
            }
            case 4: {
                impl.endTextInput();
                return new Uint8Array(0);
            }
            case 5: {
                impl.scheduleRender();
                return new Uint8Array(0);
            }
            case 6: {
                const a0 = Types.bool.decode(r);
                impl.setColorScheme(a0);
                return new Uint8Array(0);
            }
            case 7: {
                return encodeWith(Types.double, impl.now());
            }
            case 8: {
                const a0 = Types.string.decode(r);
                return encodeWith(Types.bytes, impl.rasterize(a0));
            }
            case 9: {
                const a0 = Types.string.decode(r);
                return encodeWith(StoredValueType, impl.storageGet(a0));
            }
            case 10: {
                const a0 = Types.string.decode(r);
                const a1 = Types.string.decode(r);
                impl.storageSet(a0, a1);
                return new Uint8Array(0);
            }
            case 11: {
                const a0 = Types.string.decode(r);
                impl.log(a0);
                return new Uint8Array(0);
            }
            case 12: {
                const a0 = Types.string.decode(r);
                impl.openURL(a0);
                return new Uint8Array(0);
            }
            case 13: {
                const a0 = Types.string.decode(r);
                const a1 = Types.string.decode(r);
                impl.platformCommand(a0, a1);
                return new Uint8Array(0);
            }
            case 14: {
                return encodeWith(Types.double, impl.epochMillis());
            }
            case 15: {
                const a0 = Types.bytes.decode(r);
                impl.renderTree(a0);
                return new Uint8Array(0);
            }
        }
        throw new SwiftError("unknown method ordinal");
    };
}
export class SwiftUI {
    runtime;
    /** @internal */
    constructor(runtime) {
        this.runtime = runtime;
    }
    p2prcRequestComplete(requestID, ok, payload) {
        const b2 = stageString(this.runtime, payload);
        this.runtime.call("swift_ffi_swiftui_p2prcRequestComplete", requestID, ok ? 1 : 0, b2.ptr, b2.len);
        b2.drop();
    }
    p2prcEvent(kind, payload) {
        const b0 = stageString(this.runtime, kind);
        const b1 = stageString(this.runtime, payload);
        this.runtime.call("swift_ffi_swiftui_p2prcEvent", b0.ptr, b0.len, b1.ptr, b1.len);
        b0.drop();
        b1.drop();
    }
    gpuConnect(host) {
        const f0 = host instanceof SwiftGPUWebHost ? [host.borrowHandle(), 0] : [0, registerForeign(host)];
        this.runtime.call("swift_ffi_swiftui_gpuConnect", f0[0], f0[1]);
    }
    uuiSetDisplayScale(scale) {
        this.runtime.call("swift_ffi_swiftui_uuiSetDisplayScale", scale);
    }
    uuiStart(host, renderer, width, height) {
        const f0 = host instanceof SwiftWebHost ? [host.borrowHandle(), 0] : [0, registerForeign(host)];
        const b1 = stageString(this.runtime, renderer);
        this.runtime.call("swift_ffi_swiftui_uuiStart", f0[0], f0[1], b1.ptr, b1.len, width, height);
        b1.drop();
    }
    uuiRender() {
        this.runtime.call("swift_ffi_swiftui_uuiRender");
    }
    uuiSetScenePhase(phase) {
        const b0 = stageString(this.runtime, phase);
        this.runtime.call("swift_ffi_swiftui_uuiSetScenePhase", b0.ptr, b0.len);
        b0.drop();
    }
    uuiOpenURL(url) {
        const b0 = stageString(this.runtime, url);
        this.runtime.call("swift_ffi_swiftui_uuiOpenURL", b0.ptr, b0.len);
        b0.drop();
    }
    uuiPointerEvent(kind, x, y) {
        this.runtime.call("swift_ffi_swiftui_uuiPointerEvent", kind, x, y);
    }
    uuiWheelEvent(x, y, deltaX, deltaY) {
        this.runtime.call("swift_ffi_swiftui_uuiWheelEvent", x, y, deltaX, deltaY);
    }
    uuiResize(width, height) {
        this.runtime.call("swift_ffi_swiftui_uuiResize", width, height);
    }
    uuiTextChanged(text) {
        const b0 = stageString(this.runtime, text);
        this.runtime.call("swift_ffi_swiftui_uuiTextChanged", b0.ptr, b0.len);
        b0.drop();
    }
    uuiTextSubmitted() {
        this.runtime.call("swift_ffi_swiftui_uuiTextSubmitted");
    }
    uuiTextEnded() {
        this.runtime.call("swift_ffi_swiftui_uuiTextEnded");
    }
    uuiHostEvent(id, value) {
        const b0 = stageString(this.runtime, id);
        const b1 = stageString(this.runtime, value);
        this.runtime.call("swift_ffi_swiftui_uuiHostEvent", b0.ptr, b0.len, b1.ptr, b1.len);
        b0.drop();
        b1.drop();
    }
}
/** Instantiates the reactor and returns the bridged API. `wasi`
 * merges over the built-in WASI shim, so a host can extend or
 * replace individual calls (clocks, fds, …) without forking. */
export async function load(wasm, options) {
    let memory;
    let runtime;
    // Dispatches Swift's calls on foreign proxies / closures to the
    // registered consumer implementations. Buffers arrive as (ptr, len)
    // and return packed as (len << 32) | ptr with bytes from swift_ffi_swiftui_alloc.
    const foreignBytes = (ptr, len) => len === 0 ? new Uint8Array(0) : new Uint8Array(memory.buffer, ptr, len).slice();
    const foreignString = (ptr, len) => len === 0 ? "" : decoder.decode(new Uint8Array(memory.buffer, ptr, len));
    const packForeignBytes = (bytes) => {
        if (bytes.length === 0)
            return 0n;
        const ptr = runtime.call("swift_ffi_swiftui_alloc", bytes.length);
        new Uint8Array(memory.buffer, ptr, bytes.length).set(bytes);
        return (BigInt(bytes.length) << 32n) | BigInt(ptr >>> 0);
    };
    const packForeignString = (value) => packForeignBytes(encoder.encode(value));
    const swiftFFIImports = {
        "swift_ffi_swiftui_closure_invoke": (id, argsPtr, argsLen) => {
            const dispatcher = foreignObjects.get(id);
            let result;
            try {
                result = dispatcher(foreignBytes(argsPtr, argsLen));
            }
            catch (error) {
                result = encodeErrorBlob(error instanceof Error ? error.message : String(error));
            }
            return packForeignBytes(result);
        },
        "swift_ffi_swiftui_foreign_release": (id) => {
            foreignObjects.delete(id);
        },
        "swift_ffi_swiftui_dependency_get": (keyPtr, keyLen) => {
            const dep = options?.dependencies?.[foreignString(keyPtr, keyLen)];
            if (!dep)
                return 0n;
            const id = registerForeign(dep.dispatcher);
            return (BigInt(dep.lazy ? 1 : 0) << 48n) | (BigInt(dep.ordinal) << 32n) | BigInt(id >>> 0);
        },
        "swift_ffi_swiftui_foreign_GPUWebHost_gpuCreateTexture": (id, p0, p1, p2, p3, p3_len) => {
            foreignObjects.get(id).gpuCreateTexture(p0, p1, p2, foreignBytes(p3, p3_len));
        },
        "swift_ffi_swiftui_foreign_GPUWebHost_gpuDestroyTexture": (id, p0) => {
            foreignObjects.get(id).gpuDestroyTexture(p0);
        },
        "swift_ffi_swiftui_foreign_GPUWebHost_gpuBeginFrame": (id, p0, p1, p2, p3) => {
            foreignObjects.get(id).gpuBeginFrame(p0, p1, p2, p3);
        },
        "swift_ffi_swiftui_foreign_GPUWebHost_gpuSetTransform": (id, p0, p0_len) => {
            foreignObjects.get(id).gpuSetTransform(foreignBytes(p0, p0_len));
        },
        "swift_ffi_swiftui_foreign_GPUWebHost_gpuDrawTextured": (id, p0, p1, p1_len) => {
            foreignObjects.get(id).gpuDrawTextured(p0, foreignBytes(p1, p1_len));
        },
        "swift_ffi_swiftui_foreign_GPUWebHost_gpuDrawColor": (id, p0, p0_len) => {
            foreignObjects.get(id).gpuDrawColor(foreignBytes(p0, p0_len));
        },
        "swift_ffi_swiftui_foreign_GPUWebHost_gpuDrawRects": (id, p0, p0_len) => {
            foreignObjects.get(id).gpuDrawRects(foreignBytes(p0, p0_len));
        },
        "swift_ffi_swiftui_foreign_GPUWebHost_gpuSetScissor": (id, p0, p1, p2, p3) => {
            foreignObjects.get(id).gpuSetScissor(p0, p1, p2, p3);
        },
        "swift_ffi_swiftui_foreign_GPUWebHost_gpuClearScissor": (id) => {
            foreignObjects.get(id).gpuClearScissor();
        },
        "swift_ffi_swiftui_foreign_GPUWebHost_gpuEndFrame": (id) => {
            foreignObjects.get(id).gpuEndFrame();
        },
        "swift_ffi_swiftui_foreign_WebHost_measureText": (id, p0, p0_len, p1, p2, p3) => {
            return packForeignBytes(encodeWith(TextMetricsType, foreignObjects.get(id).measureText(foreignString(p0, p0_len), p1, p2, p3)));
        },
        "swift_ffi_swiftui_foreign_WebHost_imageInfo": (id, p0, p0_len, p1) => {
            return packForeignBytes(encodeWith(ImageInfoValueType, foreignObjects.get(id).imageInfo(foreignString(p0, p0_len), p1 !== 0)));
        },
        "swift_ffi_swiftui_foreign_WebHost_syncHostViews": (id, p0, p0_len) => {
            foreignObjects.get(id).syncHostViews(foreignString(p0, p0_len));
        },
        "swift_ffi_swiftui_foreign_WebHost_beginTextInput": (id, p0, p0_len, p1, p2, p3, p4, p5) => {
            foreignObjects.get(id).beginTextInput(foreignString(p0, p0_len), p1, p2, p3, p4, p5);
        },
        "swift_ffi_swiftui_foreign_WebHost_endTextInput": (id) => {
            foreignObjects.get(id).endTextInput();
        },
        "swift_ffi_swiftui_foreign_WebHost_scheduleRender": (id) => {
            foreignObjects.get(id).scheduleRender();
        },
        "swift_ffi_swiftui_foreign_WebHost_setColorScheme": (id, p0) => {
            foreignObjects.get(id).setColorScheme(p0 !== 0);
        },
        "swift_ffi_swiftui_foreign_WebHost_now": (id) => {
            return foreignObjects.get(id).now();
        },
        "swift_ffi_swiftui_foreign_WebHost_rasterize": (id, p0, p0_len) => {
            return packForeignBytes(foreignObjects.get(id).rasterize(foreignString(p0, p0_len)));
        },
        "swift_ffi_swiftui_foreign_WebHost_storageGet": (id, p0, p0_len) => {
            return packForeignBytes(encodeWith(StoredValueType, foreignObjects.get(id).storageGet(foreignString(p0, p0_len))));
        },
        "swift_ffi_swiftui_foreign_WebHost_storageSet": (id, p0, p0_len, p1, p1_len) => {
            foreignObjects.get(id).storageSet(foreignString(p0, p0_len), foreignString(p1, p1_len));
        },
        "swift_ffi_swiftui_foreign_WebHost_log": (id, p0, p0_len) => {
            foreignObjects.get(id).log(foreignString(p0, p0_len));
        },
        "swift_ffi_swiftui_foreign_WebHost_openURL": (id, p0, p0_len) => {
            foreignObjects.get(id).openURL(foreignString(p0, p0_len));
        },
        "swift_ffi_swiftui_foreign_WebHost_platformCommand": (id, p0, p0_len, p1, p1_len) => {
            foreignObjects.get(id).platformCommand(foreignString(p0, p0_len), foreignString(p1, p1_len));
        },
        "swift_ffi_swiftui_foreign_WebHost_epochMillis": (id) => {
            return foreignObjects.get(id).epochMillis();
        },
        "swift_ffi_swiftui_foreign_WebHost_renderTree": (id, p0, p0_len) => {
            foreignObjects.get(id).renderTree(foreignBytes(p0, p0_len));
        },
    };
    const imports = {
        wasi_snapshot_preview1: wasiShim(() => {
            if (!memory)
                throw new Error("wasm memory accessed before instantiation");
            return memory;
        }, options?.wasi),
        swift_ffi: swiftFFIImports,
    };
    const module = wasm instanceof WebAssembly.Module ? wasm : await WebAssembly.compile(wasm);
    const instance = await WebAssembly.instantiate(module, imports);
    memory = instance.exports.memory;
    instance.exports._initialize();
    runtime = new Runtime(instance.exports, "swift_ffi_swiftui_");
    if (options?.dependencies) {
        runtime.call("swift_ffi_swiftui_install_dependencies");
    }
    return new SwiftUI(runtime);
}
